// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpu0ChxAIeqFC-qcRrbyVQyyAkjuAwVo4',
    appId: '1:479495155434:web:2eb2fe46fc724641d2b193',
    messagingSenderId: '479495155434',
    projectId: 'flutter-firebase-99180',
    authDomain: 'flutter-firebase-99180.firebaseapp.com',
    storageBucket: 'flutter-firebase-99180.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvDNhuUp1msEw_lK5WpiHNvfSoKyBaYc',
    appId: '1:479495155434:android:9f02510aa1828dabd2b193',
    messagingSenderId: '479495155434',
    projectId: 'flutter-firebase-99180',
    storageBucket: 'flutter-firebase-99180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrzjKWi_x2sR7yWaMd5in75MxFIDuZWE0',
    appId: '1:479495155434:ios:2af27b3d968250d4d2b193',
    messagingSenderId: '479495155434',
    projectId: 'flutter-firebase-99180',
    storageBucket: 'flutter-firebase-99180.appspot.com',
    iosClientId: '479495155434-e5pfdkoe6fsbtaavf13bnp148j09hfv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrzjKWi_x2sR7yWaMd5in75MxFIDuZWE0',
    appId: '1:479495155434:ios:2af27b3d968250d4d2b193',
    messagingSenderId: '479495155434',
    projectId: 'flutter-firebase-99180',
    storageBucket: 'flutter-firebase-99180.appspot.com',
    iosClientId: '479495155434-e5pfdkoe6fsbtaavf13bnp148j09hfv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
